# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Practice_Name', models.CharField(max_length=200)),
                ('Practice_Address', models.CharField(max_length=200)),
                ('Recovery_Phrase', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Practice_Name', models.CharField(max_length=200)),
                ('Practice_Address', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Associated_Doctors', models.ManyToManyField(to='app.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='System_Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
