# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171001_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='created_by',
            new_name='Username',
        ),
    ]
