# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20171001_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200)),
                ('Company_Address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Practice_Name', models.CharField(max_length=200)),
                ('Practice_Address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('DOB', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('Record_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Record_Date', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('Edit_Permissions', models.ManyToManyField(related_name='Edit_Permissions', to=settings.AUTH_USER_MODEL)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to=settings.AUTH_USER_MODEL)),
                ('View_Permissions', models.ManyToManyField(related_name='View_Permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Date',
        ),
        migrations.AddField(
            model_name='nurse',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medical_administrator',
            name='Associated_Doctors',
            field=models.ManyToManyField(to='app.Doctor'),
        ),
        migrations.AddField(
            model_name='medical_administrator',
            name='Associated_Nurses',
            field=models.ManyToManyField(to='app.Nurse'),
        ),
        migrations.AddField(
            model_name='medical_administrator',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
