# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171001_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Record_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
